apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskai-backend
  labels:
    app: taskai-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskai-backend
  template:
    metadata:
      labels:
        app: taskai-backend
    spec:
      containers:
      - name: taskai-backend
        image: your-docker-username/taskai-backend:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MONGODB_URI
          value: "your-mongodb-connection-string"
        - name: JWT_SECRET
          value: "your-jwt-secret"
        - name: OPENAI_API_KEY
          value: "your-openai-api-key"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"