apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskai-frontend
  labels:
    app: taskai-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskai-frontend
  template:
    metadata:
      labels:
        app: taskai-frontend
    spec:
      containers:
      - name: taskai-frontend
        image: your-docker-username/taskai-frontend:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://taskai-backend/api"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://taskai-backend/api/ws"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"